### ISSUE TITLE
How to add label file when executing the algorithm?

### ISSUE THREAD

**Issue by vrodriguezf** [mast-group/sequence-mining#2]
Hi,

I wonder if it is possible to include a `.lab` file when calling the algorithm in order to see the results in terms of labels instead of numbers.

Many thanks for your great work.
Best!
Víctor

**Comment by jfowkes** [comment]
Hello, I'm afraid that hasn't been implemented. We just wrote a Python script that read the labels and created a label to ID dictionary. You can then save the dictionary in plaintext to get a .lab file. To go backwards once you’ve mined the sequences, you simply invert the dictionary once you’ve read it in.

**Comment by vrodriguezf** [comment]
Alright, thank you for your prompt response!
