### ISSUE TITLE
Non-parseable POM 

### ISSUE THREAD

**Issue by joseph-mutu** [mast-group/sequence-mining#5]
Hi,

Thank you for your work.

when I try to run `mvn package`, it shows an error. 'Non-parseable POM'
![image](https://user-images.githubusercontent.com/27173334/56796324-97fab200-6812-11e9-8947-68dfaabe8f17.png)
it mentiones this part in the pom
![image](https://user-images.githubusercontent.com/27173334/56796068-16a31f80-6812-11e9-884d-78690ba5946c.png)

Any suggestions here?

Many thanks!

Bests,

**Comment by jfowkes** [comment]
Hmm... this is very strange, the POM used to parse no problem. Could you try an earlier version of maven? It may be that they changed the POM syntax or made the parser stricter in the latest maven.

**Comment by joseph-mutu** [comment]
Thank you for your advices. I roll back to 3.5.3 and it works.
Here is some infomation for following people:
Maven version: 3.5.3(The latest maven 3.6.1 may lead to some problems)
Java version: 1.8.0_191

Thanks,
Have a nice day:)

Bests,
